### ISSUE TITLE
Allowing user to switch between operators

### ISSUE THREAD

**Issue by realslimshanky** [realslimshanky/Dynamic-Calculator#2]
Let's say user has entered some values because of which the result becomes `123 + 321 = 444`
Allow user to change the operation by simply clicking, touching or pressing any other operator (say `-`)
according which result should also change (say `123 - 321 = -198`)

**Comment by edmgt** [comment]
Hi I think I've made a change that would allow to change operators, but when I try to make a pull request I get the following 

It's my first pull request on github so if I'm doing something wrong please point me to the right direction, thanks :)

**EDIT:** Sorry I didn't know that I had to fork before creating a pull request.

**Comment by realslimshanky** [comment]
It's okay. Mistakes are allowed until you are learning from them.

**Comment by realslimshanky** [comment]
Merge Complete
